version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}  # Use dev Dockerfile by default, can be overridden
    container_name: react-frontend  # Optional: Name the container for easier reference
    ports:
      - "5173:5173"  # Expose frontend on port 5173
    volumes:
      - ./frontend:/app  # Mount frontend code to /app inside the container
      - /app/node_modules  # Persist node_modules to avoid rebuilding it each time
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fix for file watching on some systems (useful for live reloading)
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend  # Path to the backend folder
      dockerfile: Dockerfile  # Dockerfile name (assumed it's in the backend folder)
    container_name: django-backend  # Optional: Name the backend container
    volumes:
      - ./backend:/app  # Mount backend folder to /app inside container
    ports:
      - "8000:8000"  # Expose backend on port 8000
    environment:
      - DEBUG=1  # Enable debug mode (set to 0 for production)
    networks:
      - mynetwork  # Network shared with frontend and database


# Shared network for the frontend, backend, and database containers
networks:
  mynetwork:
    driver: bridge  # Default network driver
