# Generated by Django 5.1.4 on 2025-01-10 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
