# Generated by Django 5.1.4 on 2025-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_users_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_requests',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
